using TaskerFSBlazor.Data;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Authorization;
using TaskerFSBlazor.Client.Models;
using TaskerFSBlazor.Models;
using Microsoft.EntityFrameworkCore;

namespace TaskerFSBlazor.Controllers
{
    [Route("api/[controller]")]
    [ApiController]
    [Authorize]
    public class TaskerItemController : ControllerBase
    {
        private readonly ApplicationDbContext _context;
        private readonly UserManager<ApplicationUser> _userManager;

        public TaskerItemController(ApplicationDbContext context, UserManager<ApplicationUser> userManager)
        {
            _context = context;
            _userManager = userManager;
        }

        // GET: api/TaskerItem
        [HttpGet]
        public async Task<ActionResult<IEnumerable<TaskerItem>>> GetTaskerItems()
        {
            var userId = _userManager.GetUserId(User);
            var dbTaskerItems = await _context.TaskerItems.Where(t => t.UserId == userId).ToListAsync();

            // DbTaskerItem inherits from TaskerItem, only the properties in TaskerItem will be serialized
            // hence we can return the list of DbTaskerItem directly
            return dbTaskerItems;
        }

        // POST: api/TaskerItem
        [HttpPost]
        public async Task<ActionResult<TaskerItem>> PostDbTaskerItem([FromBody] TaskerItem taskerItem)
        {
            var userId = _userManager.GetUserId(User);
            var dbTaskerItem = new DbTaskerItem
            {
                // Id = taskerItem.Id, // Id will be generated by the database
                Name = taskerItem.Name,
                IsComplete = taskerItem.IsComplete,
                UserId = userId
            };

            _context.TaskerItems.Add(dbTaskerItem);
            await _context.SaveChangesAsync();

            return Ok();
        }
    }
}